version: "3.8"

services:
  database:
    image: postgres:15-alpine
    container_name: pern_postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: pern_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pern-network

  server:
    build: ./server
    container_name: pern_server
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_NAME=pern_db
      - DB_HOST=database
      - DB_PORT=5432
      - PORT=5000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - pern-network

  client:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=http://3.25.68.244:5001
    container_name: pern_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - pern-network

volumes:
  pgdata:

networks:
  pern-network:
    driver: bridge
